#!/usr/bin/env bash
# init-env.sh - create .env with random secrets for the Graylog stack.
#
# The Graylog admin password is read from the terminal (hidden) or, when stdin is not a
# terminal, from the first line of stdin. Only its SHA-256 digest is stored. All other
# secrets are random. The file is created with mode 0600 and never overwritten unless --force.
set -euo pipefail
umask 077

VERSION="1.0.0"
SHOW_BANNER=1
ENV_FILE=".env"
FORCE=0

# ---- banner (cosmetic: stderr only, interactive terminals only) -----------
# Bastion Ops Toolkit banner. Disable with --no-banner or NO_BANNER=1. Not shown when
# stderr is not a terminal (cron, pipes, systemd, monitoring agents).
banner_enabled() {
  (( SHOW_BANNER )) || return 1
  [[ -z ${NO_BANNER:-} || ${NO_BANNER} == 0 ]] || return 1
  [[ -t 2 ]]
}

print_banner() {
  banner_enabled || return 0
  {
    cat <<'WORDMARK'
                      _                          _            _
   __ _ _ _ __ _ _  _| |___  __ _ ___ __ ___ _ _| |_ _ _ __ _| |
  / _` | '_/ _` | || | / _ \/ _` |___/ _/ -_) ' \  _| '_/ _` | |
  \__, |_| \__,_|\_, |_\___/\__, |   \__\___|_||_\__|_| \__,_|_|
  |___/          |__/       |___/
   _                _
  | |___  __ _ __ _(_)_ _  __ _
  | / _ \/ _` / _` | | ' \/ _` |
  |_\___/\__, \__, |_|_||_\__, |
         |___/|___/       |___/

+====================================================================+
|  GRAYLOG CENTRAL LOGGING  ::  Log Collection & Security Alerts     |
+--------------------------------------------------------------------+
|  Graylog stack, TLS syslog forwarding, streams and alert rules     |
WORDMARK
    printf '|  %-64s  |\n' "v$VERSION  -  Bastion Ops Toolkit  -  by int3erlud3"
    printf '%s\n\n' '+====================================================================+'
  } >&2 || true
}

usage() {
  cat <<'USAGE'
Usage: scripts/init-env.sh [--env-file PATH] [--force] [--no-banner]

Creates PATH (default .env) from .env.example with:
  GRAYLOG_PASSWORD_SECRET     96 random characters
  GRAYLOG_ROOT_PASSWORD_SHA2  SHA-256 of the admin password you enter
  MONGODB_ROOT_PASSWORD       random
  MONGODB_GRAYLOG_PASSWORD    random
The admin password is read from the terminal, or from stdin when piped.
USAGE
}

die() { printf 'init-env: error: %s\n' "$*" >&2; exit 2; }

while (($#)); do
  case $1 in
    --env-file) [[ $# -ge 2 ]] || die "--env-file needs a value"; ENV_FILE=$2; shift 2 ;;
    --force) FORCE=1; shift ;;
    --no-banner) SHOW_BANNER=0; shift ;;
    -h|--help) print_banner; usage; exit 0 ;;
    -V|--version) print_banner; echo "init-env $VERSION"; exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
done

print_banner

if [[ -e $ENV_FILE && $FORCE -ne 1 ]]; then
  die "$ENV_FILE already exists (use --force to replace it)"
fi
command -v openssl >/dev/null || die "openssl is required"
command -v sha256sum >/dev/null || die "sha256sum is required"

rand_alnum() { # rand_alnum LENGTH
  local out=""
  while ((${#out} < $1)); do
    out+=$(openssl rand -base64 96 | tr -dc 'A-Za-z0-9')
  done
  printf '%s' "${out:0:$1}"
}

if [[ -t 0 ]]; then
  read -r -s -p "Graylog admin password (min. 12 characters): " admin_pw; echo >&2
  read -r -s -p "Repeat: " admin_pw2; echo >&2
  [[ $admin_pw == "$admin_pw2" ]] || die "passwords do not match"
else
  IFS= read -r admin_pw || true
fi
((${#admin_pw} >= 12)) || die "the admin password must have at least 12 characters"

sha=$(printf '%s' "$admin_pw" | sha256sum | cut -d' ' -f1)
unset admin_pw admin_pw2

tmp=$(mktemp "${ENV_FILE}.XXXXXX")
trap 'rm -f "$tmp"' EXIT
{
  echo "# Generated by scripts/init-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not commit."
  echo "GRAYLOG_PASSWORD_SECRET=$(rand_alnum 96)"
  echo "GRAYLOG_ROOT_PASSWORD_SHA2=$sha"
  echo "MONGODB_ROOT_PASSWORD=$(rand_alnum 40)"
  echo "MONGODB_GRAYLOG_PASSWORD=$(rand_alnum 40)"
  echo "GRAYLOG_HTTP_EXTERNAL_URI="
  echo "INPUT_BIND_ADDRESS="
  echo "OPENSEARCH_HEAP="
} >"$tmp"
chmod 600 "$tmp"
mv -f "$tmp" "$ENV_FILE"
trap - EXIT
echo "init-env: wrote $ENV_FILE (mode 0600). Log in to Graylog as 'admin' with the password you entered." >&2
